function loc = impLoc5(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   DEBUGV302ND = IMPORTFILE(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   DEBUGV302ND = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   DebugV302nd = importfile('Debug_V3-0_2nd.loc', 2, 7993);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/10/24 18:01:22

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: datetimes (%{yyyy/MM/dd HH:mm:ss}D)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{yyyy/MM/dd HH:mm:ss}D%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
loc = table(dataArray{1:end-1}, 'VariableNames', {'timeUTC','latitude_0','longitude_0','altitude_0','latitude_1','longitude_1','altitude_1','latitude_2','longitude_2','altitude_2','latitude_3','longitude_3','altitude_3','latitude_4','longitude_4','altitude_4'});

% For code requiring serial dates (datenum) instead of datetime, uncomment% the following line(s) below to return the imported dates as datenum(s).

% DebugV302nd.timeUTC=datenum(DebugV302nd.timeUTC);

